backend:
  name: github
  repo: RejoiceMoyo/comingsoon
  branch: main
  base_url: https://www.theshearchive.com
  auth_endpoint: api/auth
  auth_token_endpoint: api/callback

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Articles"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string", default: "The She Archive" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
