backend:
  name: git-gateway
  branch: main

media_folder: "backlogs/images"
public_folder: "/backlogs/images"

collections:
  - name: "backlogs"
    label: "Blog Posts"
    folder: "backlogs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", default: ["blog"], required: false }
